services:
  - type: web
    name: idot-backend
    env: node
    rootDir: IDOT.BACKEND-main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: COOKIE_SECRET
        sync: false

  - type: web
    name: idot-frontend
    env: static
    rootDir: IDOT.UI-main
    buildCommand: npm install && npm run build --prod
    staticPublishPath: frontend/static

